### ISSUE TITLE
Fusion logging is not working

### ISSUE THREAD

**Issue by tomkatsu** [lucidworks/drupal-connector#15]
Log messages in connector code are logging correctly when executed on a local environment, but do not log anything on a Fusion cluster

**Comment by bogdanv96** [comment]
Hello Tom, 
I do some investigation related to this issue and do some modification in the codebase. Those modifications can be found into [investigation/logging branch](https://github.com/lucidworks/drupal-connector/tree/investigation/logging). What I noticed is that this connector is not recognized as a Lucidwork connector and the Fusion Server is using a v2 ( I don't know exactly what that means)
![image](https://user-images.githubusercontent.com/44344883/92368933-076bfb80-f101-11ea-940d-afeeef43a8cf.png)

Unfortunately, the modification didn't fix the issue. Do you have any news from the connector team?

**Comment by tomkatsu** [comment]
I found out that the warning there is just that the connector's package path doesn't start with lucidworks. It shouldn't affect anything and is just informational.

**Comment by tomkatsu** [comment]
Does the logging branch fix the issue or is it just experimentation?

**Comment by bogdanv96** [comment]
This branch is experimentation. I will try to modify the path to start with lucidworks. I used the same approach for logging as I found into connectors examples, where the logging is working, but on this is not working.

**Comment by tomkatsu** [comment]
This was fixed and was due to Fusion configuration.
